
BLENDER="C:\Program Files\Blender Foundation\Blender 4.2\blender.exe"
DIST=../dist

all : \
    $(DIST)/bathtub.pnct \
    $(DIST)/bathtub.scene \

$(DIST)/bathtub.scene : bathtub.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "bathtub.blend:Main" "$(DIST)/pool.scene"

$(DIST)/bathtub.pnct : bathtub.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "bathtub.blend:Main" "$(DIST)/pool.pnct" 
